version: 0.2

phases:
  install:
    commands:
      - npm -g install phantomjs-prebuilt 
      - npm -g install casperjs
  build:
    commands:
      - casperjs test endpoint_test.js

artifacts:
  files:
    - '**/*'

