version: 0.2

phases:
  install:
    commands:
      - npm install  
  build:
    commands:
      - export BASE_URL=`cat env.json | python -c 'import json,sys;obj=json.load(sys.stdin);print obj["values"][0]["value"]'`
      - npm test

artifacts:
  files:
    - '**/*'

